"""
ThreatIQ Report Agent

This agent creates a clear incident report from the information
already collected by the previous agents.

The report is generated from the incident state using deterministic
Python formatting. No LLM is required.
"""

from datetime import datetime, timezone
from typing import Any, Dict, List


# ---------------------------------------------------------------------------
# HELPER: FORMAT LIST
# ---------------------------------------------------------------------------
def format_list(items: List[Any], empty_text: str = "None") -> str:
    """
    Convert a Python list into readable report text.
    """

    # Return a simple message when the list is empty.
    if not items:
        return empty_text

    # Convert every item to a readable string.
    return ", ".join(str(item) for item in items)


# ---------------------------------------------------------------------------
# BUILD INCIDENT REPORT
# ---------------------------------------------------------------------------
def build_incident_report(state: Dict[str, Any]) -> str:
    """
    Build a human-readable incident report from the current state.
    """

    # Get the main incident information.
    incident_id = state.get("incident_id", "UNKNOWN")
    threat_type = state.get("threat_type", "UNKNOWN")
    risk_score = state.get("risk_score", 0)
    risk_level = state.get("risk_level", "LOW")

    # Get indicators safely.
    indicators = state.get("indicators", {})

    # Extract commonly used indicator values.
    urls = indicators.get("urls", [])
    domains = indicators.get("domains", [])
    brands = indicators.get("brands", [])
    urgency_terms = indicators.get("urgency_terms", [])
    credential_requests = indicators.get("credential_requests", [])
    payment_requests = indicators.get("payment_requests", [])

    # Get transparent risk explanations.
    risk_reasons = indicators.get("risk_reasons", [])

    # Get recommendations generated by the Response Agent.
    recommendations = state.get("recommendations", [])

    # Get potential impact if another agent has already provided it.
    potential_impact = state.get(
        "potential_impact",
        "Potential credential theft, financial loss, or account compromise.",
    )

    # -----------------------------------------------------------------------
    # BUILD REPORT
    # -----------------------------------------------------------------------

    # Start with the report title and basic incident information.
    report_lines = [
        "THREATIQ INCIDENT REPORT",
        "=" * 60,
        "",
        f"Incident ID: {incident_id}",
        f"Threat Type: {threat_type}",
        f"Risk Score: {risk_score}/100",
        f"Risk Level: {risk_level}",
        "",
        "INDICATORS",
        "-" * 60,
        f"URLs: {format_list(urls)}",
        f"Domains: {format_list(domains)}",
        f"Brands: {format_list(brands)}",
        f"Urgency Terms: {format_list(urgency_terms)}",
        f"Credential Requests: {format_list(credential_requests)}",
        f"Payment Requests: {format_list(payment_requests)}",
        "",
        "RISK REASONS",
        "-" * 60,
    ]

    # Add every reason used to calculate the score.
    if risk_reasons:
        for reason in risk_reasons:
            report_lines.append(f"- {reason}")
    else:
        report_lines.append("- No risk factors recorded.")

    # Add potential impact.
    report_lines.extend(
        [
            "",
            "POTENTIAL IMPACT",
            "-" * 60,
            potential_impact,
            "",
            "RECOMMENDATIONS",
            "-" * 60,
        ]
    )

    # Add each recommended action.
    if recommendations:
        for index, recommendation in enumerate(recommendations, start=1):
            report_lines.append(f"{index}. {recommendation}")
    else:
        report_lines.append("No recommendations recorded.")

    # Add user investigation results.
    report_lines.extend(
        [
            "",
            "USER ACTIONS",
            "-" * 60,
        ]
    )

    # Get the adaptive investigation questions and answers.
    user_actions = state.get("user_actions", [])

    # Add each question and answer.
    if user_actions:
        for item in user_actions:
            question = item.get("question", "Unknown question")
            answer = item.get("answer")

            # Show unanswered questions clearly.
            if answer is None:
                answer_text = "Not answered"
            else:
                answer_text = str(answer)

            report_lines.append(f"- {question}")
            report_lines.append(f"  Answer: {answer_text}")
    else:
        report_lines.append("No investigation questions recorded.")

    # Add timeline.
    report_lines.extend(
        [
            "",
            "TIMELINE",
            "-" * 60,
        ]
    )

    # Get timeline events.
    timeline = state.get("timeline", [])

    # Add every recorded timeline event.
    if timeline:
        for event in timeline:
            timestamp = event.get("timestamp", "Unknown time")
            agent = event.get("agent", "unknown")
            description = event.get("event", "")

            report_lines.append(
                f"[{timestamp}] {agent}: {description}"
            )
    else:
        report_lines.append("No timeline events recorded.")

    # Add report generation time.
    report_lines.extend(
        [
            "",
            "=" * 60,
            "Report generated by ThreatIQ Report Agent.",
        ]
    )

    # Join all lines into one report string.
    return "\n".join(report_lines)


# ---------------------------------------------------------------------------
# REPORT AGENT
# ---------------------------------------------------------------------------
def report_agent(state: Dict[str, Any]) -> Dict[str, Any]:
    """
    Generate and store the final incident report.
    """

    # Build the report from the current incident state.
    report = build_incident_report(state)

    # Store the generated report inside the state.
    # This does not replace any of the required top-level state fields.
    state["incident_report"] = report

    # Create a UTC timestamp.
    timestamp = datetime.now(timezone.utc).isoformat()

    # Record Report Agent activity in the timeline.
    state.setdefault("timeline", [])
    state["timeline"].append(
        {
            "timestamp": timestamp,
            "agent": "report",
            "event": "Incident report generated.",
        }
    )

    # Return the completed state.
    return state


# ---------------------------------------------------------------------------
# DIRECT TEST
# ---------------------------------------------------------------------------
if __name__ == "__main__":
    """
    Simple standalone test.

    This test creates a realistic incident state and verifies
    that the Report Agent produces a report successfully.
    """

    # Import the incident-state initializer.
    from core.incident_state import init_incident

    # Create a test incident.
    test_state = init_incident("TEST-REPORT-001")

    # Add realistic test information.
    test_state["threat_type"] = "PHISHING"
    test_state["risk_score"] = 70
    test_state["risk_level"] = "HIGH"

    # Add indicators collected by earlier agents.
    test_state["indicators"] = {
        "urls": ["https://secure-example.com/login"],
        "domains": ["secure-example.com"],
        "brands": ["microsoft"],
        "urgency_terms": ["urgent", "immediately"],
        "credential_requests": ["password", "otp"],
        "payment_requests": [],
        "risk_reasons": [
            "Suspicious URL detected (+20)",
            "Credential request detected (+20)",
            "Urgent/threatening language detected (+10)",
        ],
    }

    # Add recommendations from the Response Agent.
    test_state["recommendations"] = [
        "Do not click or interact with the suspicious link.",
        "Change credentials if they were entered.",
        "Enable multi-factor authentication where available.",
    ]

    # Add one investigation question and answer.
    test_state["user_actions"] = [
        {
            "question": "Did you click or open the suspicious link?",
            "answer": "Yes",
        }
    ]

    # Run the Report Agent.
    result = report_agent(test_state)

    # Verify that the report was created.
    print("Report Agent test successful.")
    print(f"Report generated: {bool(result.get('incident_report'))}")
    print(f"Report characters: {len(result['incident_report'])}")
    print(f"Timeline events: {len(result['timeline'])}")
